// <auto-generated />
using System;
using MagicEye2.Services.BackEndAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MagicEye2.Services.BackEndAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240928200022_dos")]
    partial class dos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MagicEye2.Services.BackEndAPI.Models.Cliente", b =>
                {
                    b.Property<int>("ClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClienteId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClienteId");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("MagicEye2.Services.BackEndAPI.Models.Expediente", b =>
                {
                    b.Property<int>("ExpedienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExpedienteId"));

                    b.Property<DateTime>("Fechaexp")
                        .HasColumnType("datetime2");

                    b.HasKey("ExpedienteId");

                    b.ToTable("Expedientes");
                });

            modelBuilder.Entity("MagicEye2.Services.BackEndAPI.Models.ExpedienteCliente", b =>
                {
                    b.Property<int>("ExpedienteId")
                        .HasColumnType("int");

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.HasKey("ExpedienteId", "ClienteId");

                    b.HasIndex("ClienteId");

                    b.ToTable("ExpedienteClientes");
                });

            modelBuilder.Entity("MagicEye2.Services.BackEndAPI.Models.MaestroTBeneficiario", b =>
                {
                    b.Property<int>("MaestroTBeneficiarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaestroTBeneficiarioId"));

                    b.Property<string>("Codigo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaestroTBeneficiarioId");

                    b.ToTable("MaestroTBeneficiarios");
                });

            modelBuilder.Entity("MagicEye2.Services.BackEndAPI.Models.Paciente", b =>
                {
                    b.Property<int>("PacienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PacienteId"));

                    b.Property<int>("MaestroTBeneficiarioId")
                        .HasColumnType("int");

                    b.Property<string>("PacienteName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PacienteId");

                    b.HasIndex("MaestroTBeneficiarioId");

                    b.ToTable("Pacientes");
                });

            modelBuilder.Entity("MagicEye2.Services.BackEndAPI.Models.ExpedienteCliente", b =>
                {
                    b.HasOne("MagicEye2.Services.BackEndAPI.Models.Cliente", "Cliente")
                        .WithMany("ExpedienteClientes")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MagicEye2.Services.BackEndAPI.Models.Expediente", "Expediente")
                        .WithMany("ExpedienteClientes")
                        .HasForeignKey("ExpedienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Expediente");
                });

            modelBuilder.Entity("MagicEye2.Services.BackEndAPI.Models.Paciente", b =>
                {
                    b.HasOne("MagicEye2.Services.BackEndAPI.Models.MaestroTBeneficiario", "MaestroTBeneficiario")
                        .WithMany("Pacientes")
                        .HasForeignKey("MaestroTBeneficiarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MaestroTBeneficiario");
                });

            modelBuilder.Entity("MagicEye2.Services.BackEndAPI.Models.Cliente", b =>
                {
                    b.Navigation("ExpedienteClientes");
                });

            modelBuilder.Entity("MagicEye2.Services.BackEndAPI.Models.Expediente", b =>
                {
                    b.Navigation("ExpedienteClientes");
                });

            modelBuilder.Entity("MagicEye2.Services.BackEndAPI.Models.MaestroTBeneficiario", b =>
                {
                    b.Navigation("Pacientes");
                });
#pragma warning restore 612, 618
        }
    }
}
