// <auto-generated />
using MagicEye2.Services.BackEndAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MagicEye2.Services.BackEndAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240318211401_migracion1")]
    partial class migracion1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MagicEye2.Services.BackEndAPI.Models.Proceso", b =>
                {
                    b.Property<int>("ProcesoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProcesoId"));

                    b.Property<bool>("ExpedientesOrdYNumeradosOK")
                        .HasColumnType("bit");

                    b.Property<string>("MesAnioProceso")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VersionId")
                        .HasColumnType("int");

                    b.HasKey("ProcesoId");

                    b.HasIndex("VersionId");

                    b.ToTable("Procesos");
                });

            modelBuilder.Entity("MagicEye2.Services.BackEndAPI.Models.VersionSecaf", b =>
                {
                    b.Property<int>("VersionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VersionId"));

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VersionId");

                    b.ToTable("VersionSecafs");
                });

            modelBuilder.Entity("MagicEye2.Services.BackEndAPI.Models.Proceso", b =>
                {
                    b.HasOne("MagicEye2.Services.BackEndAPI.Models.VersionSecaf", "VersionSecaf")
                        .WithMany("Procesos")
                        .HasForeignKey("VersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VersionSecaf");
                });

            modelBuilder.Entity("MagicEye2.Services.BackEndAPI.Models.VersionSecaf", b =>
                {
                    b.Navigation("Procesos");
                });
#pragma warning restore 612, 618
        }
    }
}
